// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2Io0Tan7x_QlDoEJN6fx0kmkDxnja9A',
    appId: '1:692482995764:web:c8ebd985b45f2a886a3c61',
    messagingSenderId: '692482995764',
    projectId: 'moodymorning-568d7',
    authDomain: 'moodymorning-568d7.firebaseapp.com',
    storageBucket: 'moodymorning-568d7.appspot.com',
    measurementId: 'G-XT9ZLEFEH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSFq_wRDfHJPkyKkUAjWtd6xtw0_alecM',
    appId: '1:692482995764:android:32ead7150037e3036a3c61',
    messagingSenderId: '692482995764',
    projectId: 'moodymorning-568d7',
    storageBucket: 'moodymorning-568d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsjiRAevBcp94hK7gDrE7OzlfRIc-jI68',
    appId: '1:692482995764:ios:065ee3cc6e0f277b6a3c61',
    messagingSenderId: '692482995764',
    projectId: 'moodymorning-568d7',
    storageBucket: 'moodymorning-568d7.appspot.com',
    iosClientId: '692482995764-2ijhrm78ktj0h6qiulk1h3dmgjm57olk.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodyMorning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsjiRAevBcp94hK7gDrE7OzlfRIc-jI68',
    appId: '1:692482995764:ios:da885c576cefc8bb6a3c61',
    messagingSenderId: '692482995764',
    projectId: 'moodymorning-568d7',
    storageBucket: 'moodymorning-568d7.appspot.com',
    iosClientId: '692482995764-avlqqqdbj9jm8tces195e1ssppmoedlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodyMorning.RunnerTests',
  );
}
